### ISSUE TITLE
IDs?

### ISSUE THREAD

**Issue by vasilisvg** [cashher/99-verhalen#21]
Waarom zet je overal een ID op? Zo belangrijk zijn deze dingen toch niet dat ze expliciet linkbaar moeten zijn?
https://github.com/cashher/99-verhalen/blob/dddda058401e795bfd536c6ab0a6290137faa219/index.html#L15

**Comment by cashher** [comment]
Alle onnodige IDs zijn verwijderd en er is (meer) gebruikgemaakt van CSS-selectors.
