### ISSUE TITLE
Classitis

### ISSUE THREAD

**Issue by vasilisvg** [cashher/99-verhalen#24]
Al die classes en ids heb je echt niet nodig. Probeer het eens zonder, dan leer je ineens allemaal hele krachtige en superhandige css selectors
https://github.com/cashher/99-verhalen/blob/dddda058401e795bfd536c6ab0a6290137faa219/index.html#L117

**Comment by cashher** [comment]
Alle onnodige classes zijn verwijderd en er is (meer) gebruikgemaakt van CSS-selectors.
